[package]
name = "wasm-macro"
version = "0.1.0"
authors = ["Thomas Duboucher <thomas.duboucher@thalesgroup.com>"]
description = ""
license = "MIT/Apache-2.0"
edition = "2021"

[lib]
crate-type = ["proc-macro"]

[dependencies]
quote ="1.0.33"
syn = "2.0.42"
